[package]
name = "rusty_raid"
version = "0.1.0"
authors = ["Jordan Whitehead <jordan9001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
rand = {version = "0.7.3", features = ["small_rng"]}